# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----Teste

------Teste
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------Teste--

###

# @name create-transcription
POST http://localhost:3333/videos/1a1ca57b-87a6-4df8-83ed-975ed9036f38/transcription
Content-Type: application/json

{
    "prompt": "Dracula, Navio Demeter"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "1a1ca57b-87a6-4df8-83ed-975ed9036f38",
    "temperatura": 0.5,
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}